name = "QuartoComponents"
uuid = "d518b17b-2989-42e8-8e91-ef4fbdd4c58f"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1.10"
